### ISSUE TITLE
Based on `Async-graphql`?

### ISSUE THREAD

**Issue by sunli829** [Tak-Iwamoto/rusty-gql#19]
I believe it would be more convenient to implement this based on `Async-graphql`, what do you think? 😁

**Comment by Tak-Iwamoto** [comment]
Hi, sunli829! Thanks for your comment.

First of all, async-graphql is a great library and I referred to it a lot in rusty-gql.
I originally started this project to learn GraphQL implementation and Rust myself.
Between async-graphql and rusty-gql, there are some differences.
- rusty-gql is supposed to generate Rust codes from GraphQL schema definitions. Therefore, introspection, directive locations and so on are determined from the GraphQL file, not from the Rust code.
- I created rusty-gql-cli as a crate for code generation and I don't want to rely on external libraries. Because when async-graphql is updated, the rusty-gql-cli may not work unintentionally.
- Since async-graphql generates GraphQL definitions from Rust code, we need to write those definitions in macro. rusty-gql reads these from .graphql files, which makes macro simpler. In my opinion, I want to make macro as simple as possible.

I referred async-graphql for a significant part of the implementation.
Without async-graphql, this library would not have been possible, nor would I have been able to understand how GraphQL works. I really appreciate it.
